### ISSUE TITLE
demo 是直接可用的吗?  在 oppo vivo 华为上都测试过,  第一次请求成功, 后续 requestId 都是-3 

### ISSUE THREAD

**Issue by crianzy** [Tencent/Hardcoder#1]
**VIVO**
初始化也没有成功, 
createSocket, connect failed ret:-1 fd:62 path:mmServer

执行 requestCpuHighFreq 也失败
"requestCpuHighFreq, requestId:-3, scene:101, action:1, level:1, timeoutms:10000, tid:29082, timestamp:" PRId64

**oppo**
init 成功
但是在 check_permission 时 回调返回失败:
checkpermission callback, isSuccess: false

执行 requestCpuHighFreq  前几次, requestId 正常, 后续requestId 都是-3
requestCpuHighFreq, requestId:1570676296514410

后续再多执行几次时, initHardCoder 回调 isConnectSuccess: false  同时 requestId = -3
但是过一会 又正常了   
是断开了会自动重连吗? 

**华为**
结果和 oppo 差不多一样 init 成功, 
前几次 requestCpuHighFreq requestId 正常 后续就不正常了. 
但是过一会就又好了. 

以上这些都正常吗?

**Comment by SophiaGuo** [comment]
请问是使用testapp进行测试吗？

**Comment by crianzy** [comment]
> 请问是使用testapp进行测试吗？
是的

**Comment by SophiaGuo** [comment]
testapp包名上线前修改过，厂商之前给testapp的包名加了白名单，所以出现新包不能用的情况。现已修复。
