### ISSUE TITLE
厂商端接入有相关端指南吗？

### ISSUE THREAD

**Issue by GankLi** [Tencent/Hardcoder#10]
我们开发自己端Rom， 有高通， Mtk 和 Rockchip 平台， 希望在设备端接入， 有相关的文档供参考吗？
我浏览了相关端介绍， 都是App端接入端的介绍。

**Comment by SophiaGuo** [comment]
请问rom是使用在什么硬件上呢?

**Comment by GankLi** [comment]
> 请问rom是使用在什么硬件上呢?

我们主要在一些POS设备上， 例如 酒店的收银设备，  我们碰到一些问题， 解决的思路跟Hardcoder很相似（例如： UI 加载绑到大核上， 性能会得到提高）
看了Hardcoder的接口实现， 我们希望在系统中也集成这么一整套功能， 如果再碰到相关的性能问题， 可以让客户直接使用Hardcoder的方案。

工程项目我们已经下载在研究了，  想了解下， 如果我们想集成Hardcoder 能从您这边得到一些帮助吗？

**Comment by GankLi** [comment]
@kirozhao @SophiaGuo

**Comment by GankLi** [comment]
Sorry, 平时不登陆Gmail， 今天才发现， 一直在关注github的回复。
我们使用的设备包含 高通， MTK 和 Rockchip。
主要使用的场景是 智能的Pos领域。

SophiaGuo <notifications@github.com> 于2019年10月13日周日 下午8:25写道：

**Comment by Anda001** [comment]
hardcoder的离不开服务端，服务端要生效必须要和rom厂家合作的吧？
我理解的对吗？

**Comment by SophiaGuo** [comment]
> hardcoder的离不开服务端，服务端要生效必须要和rom厂家合作的吧？
> 我理解的对吗？

是的，目前主流厂商已经接入了Hardcoder

**Comment by SophiaGuo** [comment]
你好，厂商接入指南已更新到 wiki。如有疑问，请随时联系。
