### ISSUE TITLE
厂商各种机型对 Hardcoder 的支持覆盖目前是什么情况？

### ISSUE THREAD

**Issue by sickworm** [Tencent/Hardcoder#13]
如果覆盖率低的话，接入的收益就比较有限了

另：厂商的海外版手机是否也支持 Hardcoder？

谢谢！

**Comment by SophiaGuo** [comment]
该框架目前已接入 OPPO、vivo、华为、小米、三星、魅族等主流手机厂商，覆盖 4.6 亿+ 设备量。
之前了解到的厂商没有区分海内外设备，同样支持 Hardcoder。
