### ISSUE TITLE
不同应用之间是否有影响？

### ISSUE THREAD

**Issue by AU3904** [Tencent/Hardcoder#16]
请问下 这个方案，这个方案是针对进程的吗？比如app1 提频了，只是app1受益，还是其他app也会提频？

再问下，app有多个进程，是要分进程提频吗？

**Comment by safaribest** [comment]
#11 看这个，只有前台的应用能申请。

**Comment by SophiaGuo** [comment]
申请是只有前台应用可以申请，但是cpu频率提升了，当前在cpu上执行的线程也是同样提频的。但是绑核操作是只针对请求的进程。
有多个进程的情况下每个进程都需要单独建立socket。

**Comment by AU3904** [comment]
谢谢
