### ISSUE TITLE
问题反馈：不支持华为、三星？OPPO性能提升不明显，底层socket连接不稳定？

### ISSUE THREAD

**Issue by ciqinga123** [Tencent/Hardcoder#18]
Hardcoder_testapp测试调研

# 测试机型分类

### 华为

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yom8s86fj31lp0u0ans.jpg)

### 三星

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yoj4hkqvj31m10u0h1s.jpg)

### 小米

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yonhcd8dj31pf0u0dpv.jpg)

### 魅族

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yoo02d5qj31k00u0wpo.jpg)

#### 初始化

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yoriswx5j31ke0u07it.jpg)

#### 鉴权

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yoxn6kuuj31s40u0amx.jpg)

##### 未开启hardcoder

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7yp23cd98j32520s44bz.jpg)

##### 开启hardcoder

![](https://tva1.sinaimg.cn/large/006y8mN6ly1g7ypagnbisj321w0u04dj.jpg)

开启hardcoder，性能并未得到明显提升，而且底层socket连接不稳定，容易断开，需要重新初始化。

# 测试结果分析

使用hardcoder需要满足2个条件，首先机型支持hardcoder，然后app拥有使用hardcoder的权限，才可以使用。

官方文档显示华为和三星默认支持hardcoder，不需要请求使用权限，昨天实际测试2个华为机型(系统为6.0和8.0)，一个三星(系统9.0)均不支持hardcoder。

另外测试小米和魅族，系统均为8.0，这两个机型都支持hardcoder，满足第一个使用条件，接下来需要申请使用权限，才能真正使用hardcoder。后续可以用小米测试，邮件联系小米官方人员，申请使用权限，权限下来后再进行后续性能测试。

使用OPPO测试， 机型支持hardcoder，鉴权通过，开启hardcoder之后，性能提升不明显，底层socket连接不稳定，容易断开，需要重新初始化后，再使用。

**Comment by RickAi** [comment]
三星华为可以找新更新的系统看看，很有可能是ROM不是最新的不带hc的服务
但是华为测过发现性能提升不明显

**Comment by SophiaGuo** [comment]
华为是系统版本9.1以上支持，我这边跟厂商确认好系统版本把支持的版本列一下。
效果的问题我确认一下testapp

**Comment by ciqinga123** [comment]
> 华为是系统版本9.1以上支持，我这边跟厂商确认好系统版本把支持的版本列一下。
> 效果的问题我确认一下testapp

好的，辛苦啦

**Comment by ciqinga123** [comment]
> 三星华为可以找新更新的系统看看，很有可能是ROM不是最新的不带hc的服务
> 但是华为测过发现性能提升不明显

华为使用的是6.0和8.0，三星是9.0，均不支持，我再找找更新的系统试试

**Comment by SophiaGuo** [comment]
支持机型列表已更新到FAQ；机型测试数据已更新到Benchmark
