### ISSUE TITLE
所有APP通过这个sdk和系统通讯，提出的升频请求，系统都会接受并执行吗？

### ISSUE THREAD

**Issue by ohmerhe** [Tencent/Hardcoder#2]
所有APP通过这个sdk和系统通讯，提出的升频请求，系统都会接受并执行吗？
会不会系统厂商只支持微信这样大APP的请求，对其他应用的请求直接丢掉？

**Comment by YummyLau** [comment]
厂商测具有绝对主导权，哪怕所有app接入，厂商也应该会权衡之后再分配。

**Comment by SophiaGuo** [comment]
FAQ 里面有各个厂商的接入方式。只有前台应用请求会被处理，所以同一时间只有一个 APP 可以请求资源，不存在资源竞争。厂商侧会对请求的持续时间等有兜底限制，主要是为了防止没有释放资源的情况，对已允许接入的 APP 不会有更多限制。

**Comment by ohmerhe** [comment]
了解，多谢

**Comment by lewmm** [comment]
不会的 只会接受在前台app的请求  根据cpu资源情况响应的
