### ISSUE TITLE
目前使用华为、OPPO、XiaoMi测试无效果

### ISSUE THREAD

**Issue by RickAi** [Tencent/Hardcoder#23]
使用了最新master testapp QuickStart进行测试
以下进行都无效果，startPerformance的测试时间开关hardcoder与否都差不多一致
具体测试机型信息：

机型 | 系统 | 效果
-- | -- | --
HUAWEI BKL-L09 | Android 9 | 不明显
Xiaomi MI 8 | Android 9 | 不明显
OPPO R17 | Android 8 | 不明显

其它品牌手机VIVO，三星等尚未测试

**Comment by RickAi** [comment]
@SophiaGuo 请看看什么原因，看不出优化效果
huawei手机测试时cpu频率无论是否开启hashcoder都差不多
xiaomi貌似你说的系統侧加入白名单，尚不能申请开发者测试权限
oppo需要checkpermission，三种不同机器差不多的情况

**Comment by RickAi** [comment]
上面机器都确认存在对应的 socket server，init_hardCoder成功

**Comment by SophiaGuo** [comment]
请问两次startPerformance之间有稍微停顿一下吗，因为cpu调度可能频率还没回到正常状态。如果还是有问题，可以抓trace看一下。
我使用Oppo Reno测试，使用HC的时间平均减少了约26%。

**Comment by NaptoZM** [comment]
> 请问两次startPerformance之间有稍微停顿一下吗，因为cpu调度可能频率还没回到正常状态。如果还是有问题，可以抓trace看一下。
> 我使用Oppo Reno测试，使用HC的时间平均减少了约26%。

是否可以建立一个QQ群来讨论，现在在Issue里面讨论得到反馈的时间周期有些长

**Comment by RickAi** [comment]
> > 请问两次startPerformance之间有稍微停顿一下吗，因为cpu调度可能频率还没回到正常状态。如果还是有问题，可以抓trace看一下。
> > 我使用Oppo Reno测试，使用HC的时间平均减少了约26%。
> 
> 是否可以建立一个QQ群来讨论，现在在Issue里面讨论得到反馈的时间周期有些长

@SophiaGuo 也有这个想法

**Comment by SophiaGuo** [comment]
更新了支持机型具体列表，更新了testapp增加了打开webview的场景，稍后给出benchmark。
