### ISSUE TITLE
请问下：服务端代码有无参考设计？

### ISSUE THREAD

**Issue by dingyanghuang** [Tencent/Hardcoder#24]
如题所述，我们正在尝试将Hardcoder 移植到我们自己基于 高通的平台，如果有服务端代码的参考设计就好了。 ：）

**Comment by SophiaGuo** [comment]
server.h为服务端实现参考。

**Comment by SophiaGuo** [comment]
你好，厂商接入指南已更新到 wiki。如有疑问，请随时联系。
