### ISSUE TITLE
希望测试Demo能增加一些针对音视频和WebView的提速示例

### ISSUE THREAD

**Issue by NaptoZM** [Tencent/Hardcoder#26]
由于项目需要，现在需要对音视频和WebView里面的游戏加速，希望能有这方面的Demo示例

**Comment by SophiaGuo** [comment]
这方面我正在完善。如果有需要的话可以尝试把项目 APP 的包名改为 testapp 包名进行测试。

**Comment by SophiaGuo** [comment]
WebView已添加，音视频场景因为纯使用音视频多是IO类型操作，CPU提频的效果并不明显，如果是网络视频，测试效果又比较受网速影响，不好做benchmark。这边有什么场景建议呢？

**Comment by NaptoZM** [comment]
> WebView已添加，音视频场景因为纯使用音视频多是IO类型操作，CPU提频的效果并不明显，如果是网络视频，测试效果又比较受网速影响，不好做benchmark。这边有什么场景建议呢？

我们现在的业务场景是多人视频会议或者上课，会有多个视频窗口，对资源的需求很大，如果有针对这种场景的加速Demo真的对我们会非常有帮助
