### ISSUE TITLE
请问这个功能是只有国内手机支持还是国外版本的手机也支持?

### ISSUE THREAD

**Issue by codeCacher** [Tencent/Hardcoder#3]

**Comment by SophiaGuo** [comment]
目前了解到的是没有区分海内外版本，但是 Hardcoder 依赖于手机 ROM 版本的更新，正常来说新机型都支持，旧机型要看 ROM。测试文档里面有判断是否支持的方法。

**Comment by SiberiaDante** [comment]
“该框架目前已接入 OPPO、vivo、华为、小米、三星、魅族等主流手机厂商，覆盖 4.6 亿+ 设备量。”
由此看来应该是不区分海内外，只区分设备，除非厂商的设备区分海内外！

**Comment by codeCacher** [comment]
了解了,谢谢
