### ISSUE TITLE
startPerformance, ret:-6

### ISSUE THREAD

**Issue by xingjiyuan** [Tencent/Hardcoder#33]
华为荣耀9X，HLK-AL00，EMUI6.1.1
发现集成Hardcoder后应用性能下降。
testapp，startPerformance显示toast：startPerformance, ret:-6

**Comment by SophiaGuo** [comment]
-6是断开了，请问是否请求了3个以上连接。目前华为侧做了限制，同一个应用不能超过三个连接，超过会断开连接，且不通知client端。所以client侧不知道底层连接断开仍push请求，会出现这个情况。华为已在修改，但是需等到rom更新才可用。
