### ISSUE TITLE
gradlew assembleDebug报错

### ISSUE THREAD

**Issue by neo1946** [Tencent/Hardcoder#35]
D:\Hardcoder>gradlew assembleDebug

> Configure project :libapp2sys
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is currently set to E:\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

[!] There's no any build-info values, skip injecting build-info module.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':libapp2sys'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insigh
ts.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by SophiaGuo** [comment]
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory. It is currently set to E:\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or local.properties to remove this warning.

NDK不对，尝试使用另外的版本或者重新下载。
