### ISSUE TITLE
SM只支持国内的机型吗？

### ISSUE THREAD

**Issue by martin90s** [Tencent/Hardcoder#36]
海外的机型支持吗？
我测试S10 Android Q的时候SystemProperties里并没有persist.sys.hardcoder.name 这个字段

**Comment by SophiaGuo** [comment]
刚问了三星，他们是只有国内机型支持

**Comment by martin90s** [comment]
@SophiaGuo 请问华为和小米也是这样吗？只支持国内机型

**Comment by SophiaGuo** [comment]
华为和小米是支持的
