### ISSUE TITLE
华为效果不明显

### ISSUE THREAD

**Issue by iceAnson** [Tencent/Hardcoder#4]
机型：华为p30
开启和关闭hc的日志如下：
2019-10-10 15:01:07.256 1646-2369/com.tencent.mm.hardcoder.testapp I/hardcoder.MainActivity: startPerformance, ret:175159058 take 3261 ms
2019-10-10 15:01:20.943 1646-2479/com.tencent.mm.hardcoder.testapp I/hardcoder.MainActivity: startPerformance, ret:0 take 3306 ms

不明显呀怎么破？

**Comment by codeCacher** [comment]
我使用华为p20测试,效果也不是很明显,点击 requestCpuHighFreq 按钮向系统申请提频后,频率也只是在计算的过程中有所提升,之后又回归正常频率,不过在没有申请提频的情况下,计算过程中也会提升频率,和申请提频表现基本一样.

**Comment by SophiaGuo** [comment]
testapp里面只是用了一个简单的 pitest 来模拟重度运算，实际效果可以看 trace 文件。不打开 HC 情况下系统并不会一开始就把所有大核都打开，也不会一开始就提升到最高频率。

**Comment by ciqinga123** [comment]
使用华为手机测试，需要做其他操作吗？我这 server socket name 返回为 ”“，测试两个华为机型都是这样，是我集成的步骤有问题吗？

**Comment by SophiaGuo** [comment]
华为当前是9.1以上系统支持Hardcoder。
刚更新了testapp的测试方式。Testapp的测试用例在华为上的确不明显，看了trace，在正常情况下cpu可以做到和使用Hardcoder相近的表现，所以表现不明显。但是同样的测试用例在oppo上可以达到将近30%的性能提升。稍后会构建更多测试用例给出测试数据。

**Comment by SophiaGuo** [comment]
更新了testapp，增加了打开webview的场景，稍后给出benchmark。
跟华为沟通过，普通的复杂运算上他们的cpu调度的确已经做得比较完善了，用trace对比看也能看出的确是否打开HC在普通场景上cpu的效果比较相近，所以效果不明显。
但是在一些复杂场景，比如一些多媒体长时间处理的场景上，华为侧表示在微信上Hardcoder是有比较明显的提升效果的。
