### ISSUE TITLE
registerANRCallback接口疑问

### ISSUE THREAD

**Issue by seasonmac** [Tencent/Hardcoder#40]
手机：huawei Mate20
现象：使用Hardcoder demo app，对registerANRCallback进行测试，本进程发生ANR之后，没有ANR的回调通知。

是不是华为没有对此接口实现？

**Comment by SophiaGuo** [comment]
华为是没有实现这个接口

**Comment by seasonmac** [comment]
@SophiaGuo  请教一下，对于ANR的监控，有没有好的办法？
