### ISSUE TITLE
难道这就是微信耗电的原因？

### ISSUE THREAD

**Issue by tokiii** [Tencent/Hardcoder#6]

**Comment by SophiaGuo** [comment]
Hardcoder 的对比测试结果是用约 2% 的耗电增长换取平均 10%-30% 的性能提升，这个耗电量是可以接受的。

**Comment by tokiii** [comment]
还可以，可以尝试。

**Comment by ghost** [comment]
@SophiaGuo 我作为消费者，真的不乐意见到你们所谓的为了性能提升，而去额外消耗电量。 如果每个App都额外消耗2-3%的电量，那是很可怕的。
性能作为一个双刃剑，看你们怎么对待。
作为用户，可以接受慢一点，但是一定要在电量和性能做一个均衡。

我其实习惯了微信的卡顿。但是微信耗电，一直排名前列，作为一个聊天软件，难道你不觉得太耗电是一件对用户不友好的事情吗？

有什么要紧的聊天消息，不能慢慢来吗？一定要通过增加耗电来实现你们所谓的性能提升？

问过用户的想法了吗？

如果每一个App都这样想，那可想而知，中国的App生态会堕落到如何的底部。
