### ISSUE TITLE
demo中打开HardCoder按钮没有实际功能

### ISSUE THREAD

**Issue by mortoncui** [Tencent/Hardcoder#9]
/**
         * open/close Hardcoder
         */
        hcSwitchBtn = ((Button) findViewById(R.id.hc_switch));
        hcSwitchBtn.setText(hcSwitch ? "Hardcoder state: opened" : "Hardcoder state: closed");
        hcSwitchBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                hcSwitch = hcSwitch ? false : true;
                if(hcSwitch) {
                    hcSwitchBtn.setText("Hardcoder state: opened");
                } else {
                    hcSwitchBtn.setText("Hardcoder state: closed");
                }
            }
        });

**Comment by SophiaGuo** [comment]
hcSwitch 开关控制下面的测试按钮是否打开 Hardcoder
